language: python
cache: pip
branches:
  only:
    - source
python:
  - 3.7.4
install:
  - gem install sass
  - pip install -r requirements.txt
  - git config --global user.email "laercio.serra@gmail.com"
  - git config --global user.name "lserra"
  - git clone https://github.com/getpelican/pelican-plugins
script:
  - fab publish: "Build Site"